{
 "title": "Service details",
 "tags": [
  "JVM",
  "HTTP",
  "OpenTelemetry"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(jvm_class_count,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Incoming HTTP requests (server)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "description": "HTTP server request rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{job=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "Total requests"
    }
   ]
  },
  {
   "title": "Error %",
   "type": "timeseries",
   "description": "HTTP server error ratio - ratio of requests that return 5xx",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{job=~\"$service\", http_response_status_code=~\"5..\"}[$__rate_interval])) / sum(rate(http_server_request_duration_seconds_count{job=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "Duration heatmap (color indicates the number of requests in that bucket)",
   "type": "heatmap",
   "description": "This shows the spread of the responses times. Each bucket represents an number of requests which had a response time in that bucket.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(le) (rate(http_server_request_duration_seconds_bucket{ job=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration (95% and avg)",
   "type": "timeseries",
   "description": "95th percentile and average of HTTP server request duration in seconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(histogram_quantile(0.95, sum by(le) (rate(http_server_request_duration_seconds_bucket{ job=~\"$service\"}[$__rate_interval]))))",
     "legendFormat": "p95"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_sum{job=~\"$service\"}[$__rate_interval])) / sum(rate(http_server_request_duration_seconds_count{job=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Incoming HTTP requests - per endpoint (server)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate",
     "type": "timeseries",
     "description": "HTTP server request rate",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_request_duration_seconds_count{job=~\"$service\"}[$__rate_interval])) by (http_request_method, http_route, http_response_status_code)",
       "legendFormat": "{{http_request_method}} {{http_route}} - {{http_response_status_code}}"
      }
     ]
    },
    {
     "title": "Error %",
     "type": "timeseries",
     "description": "HTTP server error ratio - ratio of requests that return 5xx",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_request_duration_seconds_count{job=~\"$service\", http_response_status_code=~\"5..\"}[$__rate_interval])) by (http_request_method,http_route) / sum(rate(http_server_request_duration_seconds_count{job=~\"$service\"}[$__rate_interval])) by (http_request_method,http_route)",
       "legendFormat": "{{http_request_method}} {{http_route}}"
      }
     ]
    },
    {
     "title": "Duration (95% and avg)",
     "type": "timeseries",
     "description": "95th percentile and average of HTTP server request duration in seconds",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(histogram_quantile(0.95, sum by(le, http_request_method,http_response_status_code, http_route) (rate(http_server_request_duration_seconds_bucket{ job=~\"$service\"}[$__rate_interval]))))",
       "legendFormat": "{{http_request_method}} {{http_route}} - {{http_response_status_code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Outgoing HTTP requests (client)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate",
     "type": "timeseries",
     "description": "HTTP server request rate",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(http_client_request_duration_seconds_count{job=~\"$service\"}[$__rate_interval])) by (server_address, server_port)",
       "legendFormat": "Total requests to: {{server_address}}:{{server_port}}"
      }
     ]
    },
    {
     "title": "Error %",
     "type": "timeseries",
     "description": "HTTP server error ratio - ratio of requests that return 5xx",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(http_client_request_duration_seconds_count{job=~\"$service\", http_response_status_code=~\"5..\"}[$__rate_interval])) by (server_address, server_port) / sum(rate(http_client_request_duration_seconds_count{job=~\"$service\"}[$__rate_interval])) by (server_address, server_port)",
       "legendFormat": "Errors from: {{server_address}}:{{server_port}}"
      }
     ]
    },
    {
     "title": "Duration (95% and avg)",
     "type": "timeseries",
     "description": "95th percentile and average of HTTP server request duration in seconds",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(histogram_quantile(0.95, sum by(le, server_address, server_port) (rate(http_client_request_duration_seconds_bucket{ job=~\"$service\"}[$__rate_interval]))))",
       "legendFormat": "p95 - {{server_address}}:{{server_port}}"
      },
      {
       "expr": "sum(rate(http_client_request_duration_seconds_sum{job=~\"$service\"}[$__rate_interval])) by (server_address,server_port)/ sum(rate(http_client_request_duration_seconds_count{job=~\"$service\"}[$__rate_interval])) by (server_address,server_port)",
       "legendFormat": "avg  - {{server_address}}:{{server_port}}"
      }
     ]
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Total threads",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_thread_count{job=~\"$service\"})",
     "legendFormat": "{{jvm_thread_state}}"
    }
   ]
  },
  {
   "title": "Non-daemon threads (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 20 },
   "targets": [
    {
     "expr": "avg(jvm_thread_count{job=~\"$service\", jvm_thread_daemon=\"false\"}) by (jvm_thread_state)",
     "legendFormat": "{{jvm_thread_state}}"
    }
   ]
  },
  {
   "title": "Daemon threads (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 20 },
   "targets": [
    {
     "expr": "avg(jvm_thread_count{job=~\"$service\", jvm_thread_daemon=\"true\"}) by (jvm_thread_state)",
     "legendFormat": "{{jvm_thread_state}}"
    }
   ]
  },
  {
   "title": "Heap usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_limit_bytes{job=~\"$service\", jvm_memory_type=\"heap\"})",
     "legendFormat": "Max heap"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{job=~\"$service\", jvm_memory_type=\"heap\"})",
     "legendFormat": "Used heap"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{job=~\"$service\", jvm_memory_type=\"heap\"})",
     "legendFormat": "Committed heap"
    }
   ]
  },
  {
   "title": "Non-heap usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_limit_bytes{job=~\"$service\", jvm_memory_type=\"non_heap\"})",
     "legendFormat": "Max non-heap"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{job=~\"$service\", jvm_memory_type=\"non_heap\"})",
     "legendFormat": "Used non-heap"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{job=~\"$service\", jvm_memory_type=\"non_heap\"})",
     "legendFormat": "Committed non-heap"
    }
   ]
  },
  {
   "title": "Garbage Collection (time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(increase(jvm_gc_duration_seconds_sum{job=~\"$service\"}[$__rate_interval])) by (jvm_gc_action, jvm_gc_name)",
     "legendFormat": "{{jvm_gc_action}} - {{jvm_gc_name}}"
    }
   ]
  },
  {
   "title": "Garbage Collection (count)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(increase(jvm_gc_duration_seconds_count{job=~\"$service\"}[$__rate_interval])) by (jvm_gc_action,jvm_gc_name)",
     "legendFormat": "{{jvm_gc_action}} - {{jvm_gc_name}}"
    }
   ]
  },
  { "title": "Tomcat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Tomcat threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "avg(http_server_tomcat_threads{job=~\"$service\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Active sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "avg(http_server_tomcat_sessions_activeSessions{job=~\"$service\"})",
     "legendFormat": "Active sessions"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Traces",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
     "targets": [
      {
       "limit": 20,
       "metricsQueryType": "range",
       "query": "{resource.service.name=\"${service}\"} | select(name,kind, status, span.http.status_code, span.http.response.status_code, span.http.url)",
       "tableType": "spans"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "New Panel",
     "type": "logs",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 121 },
     "targets": [
      {
       "expr": "{service_name=`$service`} | logfmt | line_format `\u001b[1m{{if .level }}{{alignRight 5 .level}}{{else if .severity_text}}{{alignRight 5 .severity_text}}{{end}}\u001b[0m \u001b[90m[{{alignRight 10 .service_instance_id}}{{if .thread_name}}/{{alignRight 20 .thread_name}}{{else if eq \"java\" .telemetry_sdk_language }}                    {{end}}]\u001b[0m \u001b[36m{{if .scope_name }}{{alignRight 40 .scope_name}}{{end}}{{if .exception_type}} \u001b[1;101m \u001b[0m{{end}} {{if .exception_type}}\u001b[1;91m{{.exception_type}}\u001b[0m{{end}}{{if .exception_message}} \u001b[1;91m{{.exception_message}}\u001b[0m {{end}} \u001b[0m {{__line__}} {{if .trace_id}} \u001b[37m\u001b[3m[trace_id={{.trace_id}}]{{end}}`"
      }
     ]
    }
   ]
  }
 ]
}