receivers:
  otlp:
    protocols:
      grpc:
      http:

  prometheus/otel:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: [ '0.0.0.0:8888' ]

exporters:
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

  logging/debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200

  file/devnull:
    path: /dev/null

  otlphttp:
    endpoint: http://loki:3100/otlp

  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"

  prometheusremotewrite:
    endpoint: "http://prometheus:9090/api/v1/write"

  prometheus:
    endpoint: "0.0.0.0:8889"
#    resource_to_telemetry_conversion:
#      enabled: true


processors:
  batch:
    send_batch_size: 50
    timeout: 5s

  memory_limiter:
    check_interval: 2s
    limit_mib: 400
    spike_limit_mib: 200

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors:
        - batch
        - memory_limiter
      exporters: [otlp/tempo]
    metrics/otel-collector:
      receivers: [ prometheus/otel ]
      processors:
        - batch
        - memory_limiter
      exporters: [ prometheusremotewrite ]
    metrics:
      receivers: [otlp]
      processors:
        - batch
        - memory_limiter
      exporters: [prometheusremotewrite, prometheus]
    logs:
      receivers: [otlp]
      processors:
        - batch
        - memory_limiter
      exporters: [otlphttp]