apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      derivedFields:
        # The regular expression highly depends on the data in Loki, you can fine multiple fields.
        - name: 'traceID'
          matcherRegex: "traceid[\": ]*(\\w+)"
          url: '$${__value.raw}'
          datasourceUid: Tempo
        - name: 'trace_id'
          matcherRegex: "trace_id"
          matcherType: "label"
          url: '$${__value.raw}'
          datasourceUid: Tempo
          "urlDisplayLabel": "Open Trace in traceview"