apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo:3200
    access: proxy
    editable: true
    isDefault: false
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: 'loki'
        #        tags: ['job', 'instance', 'pod', 'namespace']
        #        mappedTags: [{ key: 'service.name', value: 'service' }]
        tags: []
        mappedTags: []
        mapTagNamesEnabled: true
        spanStartTimeShift: '-5m'
        spanEndTimeShift: '5m'
        filterByTraceID: true
        filterBySpanID: false
      tracesToMetrics:
        datasourceUid: 'prometheus'
        # It is possible to add more mapping information
        #        tags: [{ key: 'service.name', value: 'service' }, { key: 'job' }]
        #        queries:
        #          - name: 'Sample query'
        #            query: 'sum(rate(tempo_spanmetrics_latency_bucket{$__tags}[5m]))'
      serviceMap:
        datasourceUid: 'prometheus'
      search:
        hide: false
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: 'loki'